### ISSUE TITLE
Today Tab

### ISSUE THREAD

**Issue by AkashPatelUAlberta** [CMPUT301F17T26/Smores#43]
- When setting a habit for a certain day, the habit will appear on Today tab on the day regardless of the start date.

**Comment by Brohammers** [comment]
Investigated this, and it seems to be that the date on the Habit itself is being set 1900 years into the future! 
![image](https://user-images.githubusercontent.com/31675499/32808421-3be140fe-c950-11e7-82ef-034652ebdba2.png)

@DLukeNelson Could you fix this? Since you were touching stats, i didnt want to modify Habit Details Activity. Then today tab will work as intended!

**Comment by Brohammers** [comment]
Once this is fixed, this bug => Don't Allowing creating habit events if the habit start date has not yet happened can also be implemented and fixed.

**Comment by Brohammers** [comment]
Actually fixed this with only a small tweak to habit details activity :) SHA 3190a285ee0d0e198d0452cb518805f123686588
